### ISSUE TITLE
Python cb_create error: local variable 'physical_interface' referenced before assignment

### ISSUE THREAD

**Issue by ygorelik** [model-driven-devops/nso-oc-services#129]
When applied translated _openconfig interfaces_ service configuration, got error:
```
Error: Python cb_action error. external error (19): Python cb_create error. local variable 'physical_interface' referenced before assignment
```
The issue seems appeared in the module [xr_interfaces.py](https://github.com/model-driven-devops/nso-oc-services/blob/37b6c903b81f2f20514cfc1eaaaeed254cd9ca24/mdd/python/translation/openconfig_xr/xr_interfaces.py#L179).
When lines 179-180 commented out the configuration commit succeeded.

**Comment by stmosher-dev** [comment]
I see the problem. We’ll get that fixed.
