### ISSUE TITLE
Assigning to self is not thread safe

### ISSUE THREAD

**Issue by waitai** [model-driven-devops/nso-oc-services#197]
When translating XR device interface configs to oc-service interfaces using package_nso_to_oc in NSO 6.0, received ALARM message from NSO: "admin@ncs# *** ALARM package-operation-failure: Assigning to self is not thread safe".

This is caused by the service create code in package_nso_to_oc assigning objects to self in main.py as follows:

```
class OCCallback(Service):
    @Service.create
    def cb_create(self, tctx: TransCtxRef, root: Root, service: ListElement, proplist: list):
        self.log.info(f'Service create: service={service._path}')
        self.service = service
        self.root = root
        self.proplist = proplist
        # Get device name from service path
        r = regex_device.search(service._path)
        self.device_name = r.group(1)
```

This self assigning issue creates a problem starting with NSO 6.0 when service callbacks are run in parallel resulting in the self attributes being shared by the callbacks in a non thread safe manner.

You can refer to this discussion at https://community.cisco.com/t5/nso-developer-hub-discussions/assigning-to-self-is-not-thread-safe/m-p/4718750#M7514 for more information.

**Comment by jasonking3** [comment]
@stmosher - this explains the issue I saw when issuing multiple json-rpc calls in the MDD ansible collection.  To workaround it, I had to serialize the json-rpc calls.  If we address this, I can remove the workaround for NSO 6.0.
