### ISSUE TITLE
XE - Implement IPv6 Interfaces

### ISSUE THREAD

**Issue by stmosher** [model-driven-devops/nso-oc-services#75]

**Comment by stmosher** [comment]
need to redo VRRP
remove VRRP from IPV4 config function
Check for IPV6 address. if none, use ipv4 VRRP old function
If yes ipv6 then, use a VRRPv3 with VRRPv2 enabled function
For any IPV6 always use VRRPv3

**Comment by stmosher-dev** [comment]
This has been implemented
